### ISSUE TITLE
Gulp tasks not working

### ISSUE THREAD

**Issue by tobiasmuecksch** [rjcarneiro/angularjs-starter#21]
Hey there,

I just cloned this repo, installed the dependencies via `npm i` and then I tried to run `gulp serve`.
The problem seems to be, that the gulp tasks are written in the old way for gulp 3, but gulp 4 is declared as dependency.

Anyways; I see this error:

```
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\aetm\Sites\angularjs-starter\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\aetm\Sites\angularjs-starter\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\aetm\Sites\angularjs-starter\gulpfile.js:61:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by rjcarneiro** [comment]
Hi,

I was working on that yesterday and the migration from gulp 3 to 4 is not done... I’ve worked a couple of hours in it without success. 

I’m going to fix that in the next following weeks. If you have a solution and if you’re able to contribute feel free to open a new pull request. 

Thanks
